identite:
  nom_court: PPC
  nom_complet: Pérennité Programmée Circulaire
  nom_association: ASSOCIATION POUR LA PERENNITE PROGRAMMEE CIRCULAIRE

adresse_postale:
  - Institut PPC - ASSOCIATION POUR LA PERENNITE PROGRAMMEE CIRCULAIRE
  - Campus Arts et Métiers de Paris
  - 151 Boulevard de l'Hôpital
  - 75013 Paris

email_public: perennite.programmee.circulaire@gmail.com

reseaux_sociaux:
  - nom: LinkedIn
    url: https://www.linkedin.com/company/association-pour-la-perennite-programmee-circulaire/
